name: Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
  pull_request:

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@v0.9.1
    with:
      image: 'ghcr.io/radiorabe/s2i-base' 
      name: 's2i-base'
      display-name: 'RaBe S2I Base Minimal'
      tags: 'minimal rhel9 rabe s2i'
